### ISSUE TITLE
Search only allows nine characters

### ISSUE THREAD

**Issue by mbland** [18F/hub#119]
Works pretty well up to nine characters, but completely stops showing results as of the tenth.

cc: @afeld

**Comment by afeld** [comment]
My hunch is that this is a red herring, and is actually a different issue

**Comment by mbland** [comment]
Found the nine character limit, `assets/js/vendor/angular-livesearch/liveSearch.js`, line 97:
```
if (search_string.length < 3 || search_string.length > 9) {
```
Thanks to @vzvenyach for helping me get into the debugger to find this needle in a haystack. He's opening an issue in mauriciogentile/angular-livesearch now.

**Comment by mbland** [comment]
I'll close this after we get some resolution on mauriciogentile/angular-livesearch#7.
