### ISSUE TITLE
Transfer TeamOps info to Hub structure

### ISSUE THREAD

**Issue by meiqimichelle** [18F/hub#150]
- [x] ubuntu printer img -- what is this for @gbinal ?
- [x] processes
- [x] resources
- [x] statements
- [x] team FAQ
- [x] readme
- [x] Ubuntu at 18F

Note: many of these resources have overlap with what's already in How To. Need to de-dup as we go.

**Comment by mbland** [comment]
These are all taken care of by now. Closing...
