### ISSUE TITLE
No response after submitting search terms

### ISSUE THREAD

**Issue by esgoodman** [18F/hub#152]
I started by trying to search for the "Where Am I?" content on the Hub and the search box didn't return any responses. So I tried the search box on a few pages:

https://hub.18f.us/guidelines/
https://hub.18f.us/how-to/
https://hub.18f.us/n00b

I couldn't get a search response from any of them, for any search terms.

**Comment by mbland** [comment]
Dup of #119.

**Comment by mbland** [comment]
Actually, I just noticed this is different; the `uglifier` introduced in #147 to compress the JavaScript seems to have broken search completely. Working on a fix.
