### ISSUE TITLE
Page edit returns 404

### ISSUE THREAD

**Issue by esgoodman** [18F/hub#153]
Hit "Edit this page" for /structure and got a 404

**Comment by mbland** [comment]
Ah, should've filed this this morning. Work-around is to click the green "Authorize on GitHub" button on the lower-right.

cc: @dhcole

**Comment by dhcole** [comment]
Just submitted this update to Prose to add a message and button to clear this up. Details here: https://github.com/prose/prose/pull/815

![screenshot 2015-02-12 22 19 27](https://cloud.githubusercontent.com/assets/170641/6181744/aa25e128-b305-11e4-9417-0fed1e0906dc.png)


I'll let this site for a bit in case anyone wants to review then merge into Prose master. @mbland can then update our hub instance of Prose.

**Comment by dhcole** [comment]
OK, prose/master has this change. @mbland should be able to `git pull` to our hub instance and be set.

**Comment by mbland** [comment]
Well, `git pull && node node_modules/gulp/bin/gulp.js`. ;-) But yes, done!
