### ISSUE TITLE
Visual Indication of Public Hub vs. Internal Hub

### ISSUE THREAD

**Issue by OriHoffer** [18F/hub#21]
@meiqimichelle @elainekamlley @gboone @leahbannon 

As we work on making the Hub both a resource for ourselves from the data-private side, we are also making some of it available to the public. From an internal perspective - should we have different designs for each instance so we know which version we're looking at? 

Do we need to have some indications on the public hub that this is a public version of things and that some of the items have been redacted? For example, should we call it "18F Public Hub"?

**Comment by mbland** [comment]
We've had the public hub labeled with the **18F Public Hub** headline for a while now. Gonna close this; if someone feels strongly about adding some other sort of visual indication, please reopen.
