### ISSUE TITLE
After logging out, can't log in from the same window

### ISSUE THREAD

**Issue by esgoodman** [18F/hub#245]
When I try to log in *in the same window* immediately after logging out, the sign-in button does not put me into the MyUSA authentication flow. It looks like hitting the button just reloads the page (https://hub.18f.us/oauth2/sign_in). I'm on Chrome, Version 41.0.2272.104 (64-bit)

If I open a new window, it works fine. 

To replicate:

Go to Hub. Log out. 
Then hit the MyUSA sign in button.

**Comment by mbland** [comment]
Yep, known issue. If you manually change the URL back to https://hub.18f.us/, it'll work.

Discussed this on `#javascript` today with @dhcole. I'm considering preparing another PR for https://github.com/bitly/google_auth_proxy to address this.

**Comment by mbland** [comment]
I've just sent out bitly/google_auth_proxy#82 to address this. I pushed a `google_auth_proxy` build containing this to the internal Hub, and the new "Log Out" link is working as you'd expect. I'll keep this issue open until that PR is closed.

**Comment by mbland** [comment]
What'd'ya know, it's already merged!
