### ISSUE TITLE
Prose.io confusion

### ISSUE THREAD

**Issue by jenniferthibault** [18F/hub#248]
n00b user story: I didn't know what prose was, and when I landed on a prose page by clicking "Edit this page," I didn't know where I had been taken (it clearly wasn't GitHub), what was happening, if I was in the right place to edit, or if the changes I made were automatically committed, or if they'd go somewhere to be approved.  I expected to go straight to GitHub when I clicked edit.

**Comment by mbland** [comment]
Yeah, going straight to GH is what that link used to do. :-) Lemme see what I can do...

**Comment by gbinal** [comment]
+1 to sticking with linking straight to github.com

**Comment by meiqimichelle** [comment]
Can this be closed @mbland ?
