### ISSUE TITLE
Public vs private bullet points are spaced differently

### ISSUE THREAD

**Issue by arowla** [18F/hub#256]
The leading between rows on this page is shorter for the top three public links, versus the rest of the (private) links. (In Chrome on OSX)

https://hub.18f.us/guidelines/

![screen shot 2015-04-14 at 4 41 41 pm](https://cloud.githubusercontent.com/assets/166715/7146945/2dbc5e60-e2c5-11e4-94a3-b2d648ac759e.png)

**Comment by mbland** [comment]
Good catch. Annoying, that.
