### ISSUE TITLE
When I click a link and log in using MyUSA (and then google), once I am logged in I am at a generic page, not the unique url I started with.

### ISSUE THREAD

**Issue by jtag** [18F/hub#288]
was my use case https://hub.18f.gov/private/acano-workflows/
accessing from home.
had to go back to slack and paste the link.

no the end of the worlds for sure. but wanted to document it.

**Comment by mbland** [comment]
Yeah, that's the state of the world after #286. I'll think to see if I can pass the path component through.

**Comment by jtag** [comment]
Is this a condition to share with MyUSA?  ie does it make difficult for the
actual link to pass through the login process? If so it seems like they
should be aware of it. cheers. jtag

On Fri, May 8, 2015 at 2:10 PM, Mike Bland <notifications@github.com> wrote:

> Yeah, that's the state of the world after #286
> <https://github.com/18F/hub/pull/286>. I'll think to see if I can pass
> the path component through.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/hub/issues/288#issuecomment-100369106>.
>



-- 

Jesse Taggert
Product Strategy, User Experience & Design Practices
18F Consulting Services | GSA
cell: 415-730-4965
18F.gsa.gov <http://18f.gsa.gov/>

**Comment by mbland** [comment]
I doubt it.
