### ISSUE TITLE
The term n00b

### ISSUE THREAD

**Issue by melodykramer** [18F/hub#366]
Does the term n00b resonate with people outside of the startup space? I am not sure, but thought I would raise the question for what I hope will be a lively discussion.

**Comment by tadhg-ohiggins** [comment]
I asked Stephanie Rivera, who didn't come from StartupLand, and she said that it wasn't familiar but that its meaning was clear from context, so that's one data point.

It would also be familiar to people who play online games, or who spend a lot of time on non-FB/non-Twitter online social activities.

**Comment by cmc333333** [comment]
I associate the word with teenage boys and a bit with brogrammers. I wouldn't expect it in a professional setting.

No offense intended!

**Comment by mbland** [comment]
Hear that, @meiqimichelle? You're a teenage brogrammer. :stuck_out_tongue_winking_eye: (She's the one who introduced the term to the Hub.)

**Comment by esgoodman** [comment]
I personally associate use of "n00b" with generally unwelcoming attitudes to newcomers. Canonical usage, in my experience: "RTFM, n00b."

**Comment by meiqimichelle** [comment]
_goes to look up RTFM_
....
oh.

I have no strong feelings on keeping the term or toasting it. Originally, I meant it as a tiny Easter egg (it was only in the url, not on the page anywhere). I see that it has migrated to the button on the hub homepage now, more in-your-face.

**Comment by afeld** [comment]
"Newbies" is the more popular term in the learning-to-code community, and is more endearing. If it's just the URL, `/onboarding/` is probably fine, if we want to change it. No strong feelings.

**Comment by cmc333333** [comment]
<3 @meiqimichelle

**Comment by annalee** [comment]
I agree that n00b has derogatory connotations and "newbie" is friendlier. But I also support @meiqimichelle's easter egging efforts, and would support a replacement joke in the url.

**Comment by esgoodman** [comment]
+1000-ing a replacement joke. I nominate @meiqimichelle to provide it!

**Comment by meiqimichelle** [comment]
Oooo, y'all might be waiting a while. My family says I'm the least funny one of the bunch ;) `Newbie` works though! Same idea, but friendlier, eh?

Or what are other 'new' things? `tadpole` ? `hatchingling` ?  Hrm, not as clear.

Or 'starting' things -- `starting-line`, `101`, `intro-to-18F`

Or 'welcome' things -- `welcome-mat`, `doorbell`

`Newbie` is likely the easier to remember/associate with the info. Your turn! What y'all think?

**Comment by jackiekazil** [comment]
:+1: n00b to newbie for reasons stated already

**Comment by cmc333333** [comment]
I'm for "neophyte"

**Comment by arowla** [comment]
+1 neophyte

**Comment by jackiekazil** [comment]
(changing my stance...) 
+1other non-newbie term.... newbie being an extension of n00b still can be alienating.  
However, neophyte -- while better isn't a word that everyone might know. For that reason, I will throw out..... 

newcomer.

**Comment by annalee** [comment]
At the risk of bikeshedding the wording, the clear choice here is Padawan.

(I'll also accept gumshoe, initiate, rookie, and any and all references to Batman or Carmen Sandiego).

**Comment by meiqimichelle** [comment]
_sees padawan references everywhere, still doesn't know what it is, assumes it is a star wars thing_

**Comment by wslack** [comment]
^^ is correct! Resurrecting this thread.

**Comment by pkarman** [comment]
ime, n00b is fine when you use it about yourself, less fine when used about others.

**Comment by wslack** [comment]
I'm cool with Padawan. (FWIW, n00b to me is endearing, but I recognize the other interpretation)

**Comment by mbland** [comment]
Vetoing "padawan" here and now. That word we never uttered in a Star Wars movie.

**Comment by mbland** [comment]
s/we/was/

**Comment by annalee** [comment]
What if they say it in Episode VII, @mbland? WHAT THEN??

**Comment by mbland** [comment]
_Will not get his hopes up..._

**Comment by melodykramer** [comment]
This is just making me giggle now.

/comment that describes emotional state but does not add value to conversation.

**Comment by esgoodman** [comment]
No "padawan" unless a Star Trek reference is also included. I demand parity! 

Actually, seriously, I think the page should be called "New to 18F."

**Comment by afeld** [comment]
https://github.com/18F/hub/pull/400

**Comment by wslack** [comment]
:+1: (but will give others a sec to check before insta-merging)
