### ISSUE TITLE
Add Training request submission guide to hub 

### ISSUE THREAD

**Issue by jackiekazil** [18F/hub#373]
Add Conference request submission guide to hub ... this doc -- https://docs.google.com/document/d/1sl6X1FueCN-L4p2P2xWU0U5_qeH75Vy-Z7M9_kOrBIQ/edit

/cc @ScottPia

**Comment by jackiekazil** [comment]
*in progress*

**Comment by ScottPia** [comment]
Quick Look Guide has been updated.  Please review for accuracy.  Please let me know if revisions are required.  If we can upload on GitHub and 18F Hub by this week -- it would be fantastic!!  Thanks Jackie for all of  your help!

**Comment by jackiekazil** [comment]
Closing this since it is as done as it will be. Let's keep future edits as separate issues as needed. See: https://hub.18f.gov/inperson-training/
