### ISSUE TITLE
newsclips - where to fit in

### ISSUE THREAD

**Issue by gbinal** [18F/hub#38]
I've been keeping a [list of 18F news clips](https://github.com/18F/team-ops/wiki/18F-in-the-News) in /team-ops, but can move them here.  Any preference as to where I put them?  I can forklift it as a page onto 18f.gsa.gov/hub easily enough but @mbland, do you have something else in mind?  

@OriHoffer, @gboone - any thoughts?  

[This is in support of https://github.com/18F/hub-pages-private/issues/3]

**Comment by meiqimichelle** [comment]
@gbinal Are the newsclips already in yml (I don't know how github wikis work)? If no, I suggest that as a first step. I could see us pulling this into several parts of the 18f site once its revamped (never fear....still in process and moving). @gboone @mbland thoughts?

**Comment by gbinal** [comment]
No, just hyperlinked in github markdown.  I'm happy to convert them but would just need to know where to put the material.

**Comment by meiqimichelle** [comment]
Got it. Well, before you spend the time doing it, I'll let @gboone and @mbland weigh in. I would imagine that the file would go....hmmm....maybe in the `data-private` repo if that is becoming our 18F data repo in general, but I might not be privy to the latest thinking there.

**Comment by gboone** [comment]
Good idea bringing this into the Hub or 18f-site. If it's just links and dates it could be yaml data. If we're going to summarize them at all it might be worth creating a [collection](http://jekyllrb.com/docs/collections/) for news clips.

**Comment by gbinal** [comment]
Let's go with yaml for now.  I've only had the bandwidth to keep track of article links and titles and am not in a position to expand that. 

FWIW, I'm not advocating adding this to the main 18f.gsa.gov.  Personally, I think that'd be a bit garish.   It's more a team resource that doesn't need to be private.

**Comment by meiqimichelle** [comment]
We'll see. It might be interesting to have just the latest news clip show
up somewhere. But yes, understood ;)

On Thu, Jan 8, 2015 at 10:20 AM, Gray Brooks <notifications@github.com>
wrote:

> Let's go with yaml for now. I've only had the bandwidth to keep track of
> article links and titles and am not in a position to expand that.
>
> FWIW, I'm not advocating adding this to the main 18f.gsa.gov. Personally,
> I think that'd be a bit garish. It's more a team resource that doesn't need
> to be private.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/hub/issues/38#issuecomment-69214069>.
>



-- 
Michelle Hertzfeld
michelle.hertzfeld@gsa.gov
520-208-3752
202-317-0155
@18F

**Comment by afeld** [comment]
> It's more a team resource that doesn't need to be private.

Sounds like a good use case for a sub-page of the Hub, then :+1: 

https://github.com/18F/hub/tree/master/pages#publicly-visible-pages

**Comment by afeld** [comment]
...and can be fed by a data file in https://github.com/18F/hub/tree/master/_data, if you like.

**Comment by gbinal** [comment]
I'm happy to put them in as yml in /_data and we can figure out what to do with them.  

Just to check, does this look okay to start? (it's the data I have, I'm just asking about format)

````
- article: Full Text Of Title
  url: http://www.publication.com/name_of_article
- article: Full Text Of Title, 2
  url: http://www.publication.com/name_of_article_2
````

**Comment by afeld** [comment]
:+1:

**Comment by gbinal** [comment]
https://github.com/18F/hub/pull/44

**Comment by gbinal** [comment]
Just to confirm, I don't plan to do individual additions to the clips.yml through pull requests but rather as direct commits.  Holler if that's any concern, @afeld, @mbland

**Comment by afeld** [comment]
Nah that's fine. But if it breaks the build, _I will find you_ :rage1: 

:wink:

**Comment by gbinal** [comment]
:)

**Comment by mbland** [comment]
@gbinal For stuff like this that's hard to screw up, that's perfectly fine. Though you may want to do something like the following for a sanity check:

```
$ ruby -e "require 'yaml'; puts YAML.load_file '_data/public/clips.yml'"
```

Whoops, I just noticed two things: One, that `_data/public` really isn't the best place for `clips.yml`. No matter; we can move it when we get ready to prepare the page. (And, I can better document that no data should be directly added to `_data/public`; it's an honest mistake and my fault for not having it better documented by now.)

Two:
```
/usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/psych-2.0.9/lib/psych.rb:370:in `parse': (_data/public/clips.yml): mapping values are not allowed in this context at line 2 column 26 (Psych::SyntaxError)
```

The first `article:` entry contains a colon. I think it needs to be wrapped in quotes. Same for lines 41, 44, 62, 80, 86, 128, 146, 158, 185, and 266. PR to fix: #46

**Comment by gbinal** [comment]
Have tried a first pass at making an html page at https://github.com/18F/hub/pull/47

@afeld, game to take a look?

**Comment by gbinal** [comment]
Like @afeld says, #47 addresses
