### ISSUE TITLE
figure out how to deal with private links

### ISSUE THREAD

**Issue by afeld** [18F/hub#413]
Unless we are very diligent about putting `{% unless site.public %}` everywhere, we are going to have links to private Hub pages, Google Docs, Slack, etc. We should figure out a good way to handle them from the public Hub.

**Comment by mbland** [comment]
I could imagine a link scanner that replaces the anchor tag and text with something like: `<em>original link text (internal-only link)</em>` or some such. However, if the entire context around a link may be worth stripping out, we're back at needing `{% unless site.public %}`.

**Comment by mtorres253** [comment]
Moving to icebox until this becomes a priority again

**Comment by afeld** [comment]
Ha, apparently I thought of this idea twice: https://github.com/18F/ideas/issues/8

**Comment by mtorres253** [comment]
Putting back in progress. Mel just needs to update contributing.md with this data

**Comment by afeld** [comment]
Psst: https://github.com/18F/private-eye
