### ISSUE TITLE
What are the weekly meetings that are on my calendar?

### ISSUE THREAD

**Issue by melodykramer** [18F/hub#417]
[This page](https://github.com/18F/hub/blob/master/_pages/qa/calendar-items.md) details some of the weekly meetings that we have at 18F.

Suggested improvements for this page:

1. Update based on current meeting schedule
2. Link to weekly meeting schedules for individual teams (Example: [design](https://hub.18f.gov/design-onboarding/))
3. Add explanations of what each weekly meeting is.

**Comment by nicoleslaw** [comment]
Covered in https://handbook.18f.gov/meetings-and-meeting-tools/
