### ISSUE TITLE
data file breaking?  

### ISSUE THREAD

**Issue by gbinal** [18F/hub#43]
Haven't learned enough about what data is supposed to go where and how so might be off on this, but by chance, are apostrophes breaking the data formatting somehow in the [team.yml file](https://github.com/18F/hub/blob/master/_data/public/team.yml)?  

The github coloration just caught my eye and made me concerned.  Notice the all read starting at the apostrophe at the end of aaron's bit and going through to the end of Alison's bit.  

![screen shot 2015-01-08 at 8 52 26 pm](https://cloud.githubusercontent.com/assets/633088/5674445/6467b43e-9778-11e4-881a-898666f0c742.png)

**Comment by afeld** [comment]
Good catch! http://stackoverflow.com/a/3790497/358804

**Comment by mbland** [comment]
This version of the data is spit out via [safe_yaml](http://www.rubydoc.info/gems/safe_yaml/1.0.4) in the [_data/import-public.rb](https://github.com/18F/hub/blob/master/_data/import-public.rb) script, so I'd be surprised. Lemme check (eliding some intermediate IRB output)...

```
$ irb
> require 'yaml'
> data = YAML.load_file '_data/public/team.yml'
> aaron = data.select {|i| i['name'] == 'aaron'}
> puts aaron[0]['bio']
is a Presidential Innovation Fellow working on the RFP-EZ project. Previously, Aaron co-founded Daring Software and built the back-end for its flagship shopping app, Arro. Prior to that, he was Web Development Manager for Birthday in a Box. He has also served as a program manager for Microsoft, an instructor for the University of Washington Extension School, a Federal law clerk, a litigation attorney for Boies, Schiller & Flexner LLP, and a manager and senior advisor for voter protection teams on two presidential campaigns. Aaron is an honors graduate of Harvard College, where he served as a Teaching Fellow in computer science, and Columbia Law School, where he was Technology Editor for the Columbia Law Review and received the Lance Liebman "Nice Guys Don't Necessarily Finish Last" Award. He lives in Kensington, MD, with his wife, their two children, and an energetic puli puppy who enjoys stealing everyone's socks.
```

Nope, don't look broke to me. Just an artifact of GitHub's pretty-printing.
