### ISSUE TITLE
The fate of /departments/ and /structure#departments

### ISSUE THREAD

**Issue by kaitlin** [18F/hub#446]
Right now we have two places that list the departments. One is on the [structure page](https://hub.18f.gov/structure/) which just says "Coming Soon". The other is the [departments page](https://hub.18f.gov/departments/) which just has links to descriptions for DevOps and Consulting. I also can't find where the Departments page is linked from. 

How do people feel about doing away with the [departments landing page](https://hub.18f.gov/departments/) and just adding the links to the departments on the structure page under the departments heading?

@melodykramer @mbland @andrewmaier  and anyone else who may be working on the site IA...

**Comment by mbland** [comment]
Some context for my comments: The current "Departments" landing page was baked into the Hub from the beginning. There's a `departments` directory in the current 18F/data-private repository, and there's a `_departments` collection in 18F/team-api.18f.gov. We just never got around to fleshing out the `departments` data model and adding any data to it.

Hence, the "Departments" page is a placeholder for _what could be_, whatever that is. I see utility in keeping a distinct "Departments" page, but I'm not wedded to the idea.

Either way, it would be nice to start fleshing out the "Departments" data model, finally, so we can expose it via the Team API and render it wherever and however we want.

**Comment by melodykramer** [comment]
@mbland - would you have time at the offsite to meet with me and @andrewmaier? We were planning to spend our time together working on the IA, and I want to make sure it aligns with the Team API and that we're all working in the same stream :+1: :100: :cake:

**Comment by ultrasaurus** [comment]
FYI:  I've had to stop using the word "Department" with agency partners, since that is a synonym for agency... you know Department of State, Dept of Commerce, Dept of Transportation... it confused people.  I think we should use the government word for whatever it is we're trying to express, or at least a different word

**Comment by mbland** [comment]
Very good point. I'm open to ideas, even if it means choosing "team" and finding a new word for "every member of 18F", which is what "team" means in the current schema.

**Comment by mbland** [comment]
How about this: We switch the current `team` field over to `people`, and use `teams` in place of what is currently meant by `departments`?

Also see the issues @jeremiak raised on 18F/about_yml, starting with 18F/about_yml#7.

**Comment by mbland** [comment]
Another possible replacement for `departments`: How does `organization` sound?

**Comment by mbland** [comment]
Shifting this topic over to 18F/team_api#19.
