### ISSUE TITLE
add "Performance *" terms to the glossary

### ISSUE THREAD

**Issue by afeld** [18F/hub#453]
Came up in [our last facilitator meeting](https://docs.google.com/document/d/1rBUkuddS7WqBAlOYthFFLbfS7QJ4zkcTrYPU2f48FiA/edit#heading=h.7h5ux8818vzg) – I constantly get confused about the difference between the Performance Plan, Performance Profile, and Performance Review, and I'm sure I'm not the only one.

Thanks!

**Comment by nicoleslaw** [comment]
Tracking in https://github.com/18F/handbook/issues/533
