### ISSUE TITLE
A few updates for "How do I sign up for training and classes?"

### ISSUE THREAD

**Issue by brittag** [18F/hub#454]
On the ["How do I sign up for training and classes?" page](https://hub.18f.gov/training-and-classes/), the link to the ["Speaking requests, attending events" spreadsheet](https://docs.google.com/spreadsheets/d/1Y0336rKQ4FiTFhoQynRjoVuJFzXEgaV0QcHqaNd-Eis/edit#gid=2072167708) goes to the "FY 2015 Training Requests" tab, but it should probably go to the "FY 2016 Training Requests" tab now. :)

(Also, the first link to a sample IDP is a Google Doc that requests you ask for permission to view it, so updating that may be helpful as well.)

**Comment by afeld** [comment]
Want to take a pass at updating it?

https://hub.18f.gov/tutorial-for-hub/

Feel free to ping me or #wg-documentation on Slack if you need any help!

**Comment by brittag** [comment]
A couple more suggestions for updating this page, while I'm working with it: it'd be helpful to link to GSA's guides to completing the SF-182 form, or just point out that they're linked in the right sidebar here: https://insite.gsa.gov/portal/content/615382

The "official training policy" link says in its Q&A that step three ("Enter your training in the event tracker on Salesforce.") isn't always necessary, so this page should probably reflect that too.

I might be able to work on this, but I'll also leave it unclaimed in case somebody else can get to it first.

**Comment by brittag** [comment]
Another suggestion as I work through this process: these documents don't seem to explain what happens after the expense is approved - whether I will purchase the training and fill out some kind of form to get reimbursed, or whether somebody else will purchase the training for me. That would be helpful to include!

**Comment by mtorres253** [comment]
Marking as content so that content team can track.

**Comment by brittag** [comment]
Adding more info as I go through these steps: my personal next step was that I got asked to fill out an 18F-specific Purchase Request Form. :) It sounds like this process may be changing soon though.

**Comment by melodykramer** [comment]
There's a document that has a draft for use on the handbook in this issue: https://github.com/18F/handbook/issues/8 - please note any changes there, because this conversation is now taking place in two places.
