### ISSUE TITLE
Instructions to add content to handbook

### ISSUE THREAD

**Issue by mtorres253** [18F/hub#459]
To give people a clear idea of how to submit suggestions for content updates, there should be easy to read instructions on how to update content somewhere that is readily accessible to users.

Acceptance criteria: the instructions on how to request content updates to the handbook should be tested with some users who are likely to want to update content. This already exists but needs an editorial flow added. 

Notes:
How does the process differ for new vs. existing content?

**Comment by melodykramer** [comment]
Draft is here: https://docs.google.com/document/d/1PZGp1iTYLCZLJ0hLJwNCZG4MgTyyJvbuAWtHIaZyTuI/edit#

**Comment by melodykramer** [comment]
Testing with Andre and Greg.
