### ISSUE TITLE
Investigate off the shelf solutions

### ISSUE THREAD

**Issue by mtorres253** [18F/hub#464]
In order for 18F to more efficiently use resources, we should not be building things that already exist somewhere else. If we can use existing technology to build the new version of the hub, we should do it. 

Acceptance criteria: This story is done when we have investigated using an off the shelf intranet software. We should look at at least two viable options (at least two members of the team sees a demo). We should create some document with our decision.

1. Ability to update content via a UI
2. Workflow allowing for content update requests and approvals
3. Custom views per user role, location, other user attributes
4. Savable checklists?
5. Tagging content
6. Be able to accept data from team API and visualize in hub

**Comment by andrewmaier** [comment]
Via @afeld:
- https://github.com/pivotal-cf/bookbinder
- https://github.com/GitbookIO/gitbook

**Comment by afeld** [comment]
Not My Circus, Not My Monkeys, but what are you looking for that the current setup doesn't do?

> we should not be building things that already exist somewhere else

This is arguably already the case for the Hub through its use of Jekyll, no?

> Ability to update content via a UI

Federalist?

> Workflow allowing for content update requests and approvals

Pull requests?

> Tagging content

Already supported in Jekyll.

**Comment by mtorres253** [comment]
Hi @afeld, based on the user research we've conducted (https://docs.google.com/document/d/1QLJvUxewYf7Ve-B-1gADfpv03w__mp_d0ovgisd-12k/edit), the current version of the hub is causing problems for users in that:

1. It's not easy to find content
2. There is a lack of consistency 
3. It's difficult for users to update

And, since there are existing intranet software options, and even some potential other options like Federalist, that already exist, we are taking some time to evaluate whether we should continue with the current hub or pursue other options. This story is to look at the other options.

**Comment by mtorres253** [comment]
Demos done with igloo and podio. Documented here:
https://docs.google.com/a/gsa.gov/document/d/19Atkm6rTq4iklShe4TobnuVbBvEh1jgoF26Gd-H1Agc/edit?usp=sharing

Along with other options
