### ISSUE TITLE
Need help porting Listservs to Handbook

### ISSUE THREAD

**Issue by andrewmaier** [18F/hub#469]
Trying to figure out what problem this content solves:

https://hub.18f.gov/private/listservs/

Is this something we should incorporate into a checklist, @melodykramer ?

**Comment by afeld** [comment]
Yep, was linked to as [part of onboarding](https://hub.18f.gov/onboarding/#email-and-listservs).

**Comment by melodykramer** [comment]
We should incorporate this into a checklist - but there still needs to be a place for people to write descriptions + join instructions + etc. We can just take the Markdown and transfer it over - if content on the Hub is eventually going to go away, we need to account for this.

**Comment by andrewmaier** [comment]
Sounds good. I'd suggest this goes into the onboarding content/guide since that's sort of where it initially lived.

I'll append it to https://handbook.18f.gov/onboarding and migrate the whole thing, okay @melodykramer ?

**Comment by melodykramer** [comment]
What links to onboarding now is going to be depreciated because it will be folded into the checklists. I would make a separate file for listservs and place it under "How we Communicate"

**Comment by andrewmaier** [comment]
The answer to this depends on our answer to https://github.com/18F/handbook/issues/80

**Comment by melodykramer** [comment]
It still needs to be ported over, I believe. If we're planning to depreciate material on the Hub, then the material on the Hub needs to live somewhere else. We'll have to figure out where it goes, but I still think it needs to move over.

**Comment by mtorres253** [comment]
This is done
