### ISSUE TITLE
Determine how to loop in rest of 18F

### ISSUE THREAD

**Issue by melodykramer** [18F/hub#471]
I see people updating the Hub. I see people updating the Handbook. There are parallels streams going, and we're not capturing everything that's being updated in the Hub. At some point, we will have to develop language around telling the team how/where to place information.

- [ ] Let's give a presentation at the all-hands
- [ ] Post something in news
- [ ] Newsletter

Message is that we are attempting to create a canonical resource where we can point new hires.

**Comment by mtorres253** [comment]
Let's discuss as a team and come up with a plan so that people can continue to contribute and the on-boarding team doesn't have to keep track of two different sources of information

**Comment by andrewmaier** [comment]
Yes. Please!

**Comment by mtorres253** [comment]
Time set aside at next all hands. Either Melody or I will announce. We need:
1. A blurb for the #news channel/newsletter to send at around the same time
2. Align on an interim process: I suggest we simply tell people that we are going to put some restrictions on merging changes in the Hub until the content tiger team/g-content come up with more formal processes. We can activate the restrictions some time after the meeting.

**Comment by andrewmaier** [comment]
Here's the information I prepared for the Town Hall which I couldn't use. Maybe we can start here and edit this down?

#### Handbook
- This concept was specifically created to address the feeling of information overload at 18F.
Presently, people at 18F primarily document things in two ways: they either create a Google Doc or contribute to our internal wiki, the Hub. That process hasn't always produced the most consistent, accessible content.
- The 18F Handbook strives to graft an editorial process onto the Hub. Based on our user research, a content audit, and an analysis of the questions asked in Slack, we started with an outline of things people need to know.
- Next we used the content generated from the Slack-based seminars as a starting point. Our knowledgable presenters did the legwork for us to link to content related to their presentations and we helped migrate it all to one place.
- We also realized that we had guidance in multiple places, so we started creating content types based on user needs. We have, for example, one place where people can learn everything they need to know about working in D.C. or everything they need to know about working remote. We've created similar content for the Tools that people use across 18F.
- We're working hard with our content team to determine how to best edit/condense the amount of documentation we produce. This will ultimately be a task shared across our organization. Mel, for example, had the idea to put an :evergreen: in Slack and that helps us figure out what needs to work its way back into the onboarding process.

**Comment by mtorres253** [comment]
This is great @andrewmaier. Thank you

**Comment by wslack** [comment]
I popped over here to open on an issue on this exact topic so I would :+1:. I can't tell right now where I'm supposed to look up stuff or put in new things I discover for inclusion in internal documentation.
