### ISSUE TITLE
include information about term extension

### ISSUE THREAD

**Issue by afeld** [18F/hub#482]
See conversation around https://18f.slack.com/archives/general-talk/p1447728049000676.

/cc @cbrydges

**Comment by andrewmaier** [comment]
I'm interested in how this plays out. From my perspective, I'd like for this to either 
1. be detailed in one of 18F's policies + procedures (as listed on https://handbook.18f.gov), or 
2. be mention in a seminar

**Comment by cbrydges** [comment]
What are you looking for here?  The whole policy and process?  Still need to figure/document that out.  The basics are 1) supervisors and staff connect 6 months out from expiration about an NTE renewal.  (Discussing is the position still needed / a priority, has the incumbent received a 3 or higher appraisal) Once they mutually agree they alert Talent that a renewal or not needs to be done.  I also still need verification from HR but I am pretty sure it is the case that it does not have to be an additional 2 years - it could be less (6 months, 1 year, etc.).  Still some tinkering to do here before a "policy/document" can be created but it is on my list.

**Comment by andrewmaier** [comment]
Sounds good, @cbrydges. Just ping me here when you've got something to share and we can work on where to get it into the Hub/Handbook.

**Comment by afeld** [comment]
@cbrydges Even putting exactly what you wrote right there into a page would be a good start. Fine if it needs to include a disclaimer like "this information is evolving – contact @cbrydges for details".

**Comment by nicoleslaw** [comment]
Closing and adding to handbook backlog: https://github.com/18F/handbook/issues/721
