### ISSUE TITLE
Clarify process to request software

### ISSUE THREAD

**Issue by afeld** [18F/hub#484]
Seems like the instructions differ, depending on where you look:

* https://18f.gsa.gov/hub/request-supplies/
* https://github.com/18F/onboarding-documents/blob/master/Checklists/buddy-checklist.md

My main question: is the process of where the person should go different depending on whether we have previously procured that particular software/service or not? As a whole, I'm not sure what the real answer is or should be – just wanted to raise the issue that the information is inconsistent, and probably incomplete.

Would someone mind CC-ing whatever #teamops / #acquisition people would be relevant here? Thanks!

/cc @melodykramer @NoahKunin @kimberbat https://github.com/18F/hub-pages-private/pull/85

**Comment by melodykramer** [comment]
I will clarify in the Buddy checklist and make sure the information is updated in the Handbook, [here](https://github.com/18F/handbook/blob/staging/articles/5-training-and-professional-development/seminars/gsa-tools.md#equipment)

**Comment by melodykramer** [comment]
And yes, I think the answer differs based on the question you asked. I based my response on the buddy checklist based on the information [here](https://hub.18f.gov/design-onboarding/) which indicates how to obtain software that has already been procured.

**Comment by melodykramer** [comment]
I'll adjust for both scenarios in the handbook, so we have a complete and consistent process articulated.

**Comment by melodykramer** [comment]
@afeld I updated and this should be fixed. :)

**Comment by afeld** [comment]
@melodykramer Sorry, updated it where?

* [ ] Document the process in a single canonical place
* [ ] Link to that place from the others listed in this issue

**Comment by afeld** [comment]
Sorry, just saw https://github.com/18F/handbook/pull/147.
