### ISSUE TITLE
Create redirects for deprecated hub content

### ISSUE THREAD

**Issue by andrewmaier** [18F/hub#489]
The Handbook is quickly outpacing the Hub in terms of its depth, as opposed to its breadth, of content. It'll soon be the canonical reference for essential things at 18F. (This is by design.) Because outdated documentation is worse than no documentation at all, it's essential that we redirect people who visit outdated Hub pages to their more contemporary Handbook equivalents.
(see https://docs.google.com/a/gsa.gov/spreadsheets/d/1RlpKa4_opsNfAizQrlv_RDizHZMfgqMjnYsOVwJ8pEQ/edit?usp=sharing for redirect info)

#### Acceptance criteria
- Hub/Handbook administrators will need a way to flag Hub content as deprecated.

- When someone visits [a deprecated Hub page for which their is a Handbook equivalent](https://docs.google.com/spreadsheets/d/1jlxvVbnmVq_i3FDWZvl-TQmzADYo7EH7VUkJvQOX9Xo/edit#gid=0), the Hub should automatically redirect them to the most recent content. 

- I think we should use the same tech that handbook-urls uses to redirect Hub pages to the Handbook. So, for example, if someone visits https://hub.18f.gov/github-work/ we should auto-redirect them to handbook.18f.gov/github . Maybe @jeremiak can help us do this?

--

This is related, and I can make a separate story for it if you'd like. Mel also suggested "a Slack auto-message that redirects people if they use the old link," which I like. I don't know how hard it is to setup autoresponders, but we could do that for the top 10 Hub URLs people share. Thoughts?

**Comment by mtorres253** [comment]
Slack bot is already a separate story. Though I don't see a need for it if we have redirects in place
