### ISSUE TITLE
Add link to GitHub activity as snippet aid

### ISSUE THREAD

**Issue by mbland** [18F/hub#49]
Migrated from 18F/hub-original#26. From original issue:

Per @afeld's idea:

https://github.com/search?utf8=%E2%9C%93&q=user%3A18f+created%3A%222014-11-22+..+2014-11-30%22+author%3AUSERNAME&type=Issues&ref=searchresults

**Comment by afeld** [comment]
Moved to https://github.com/18F/tock/issues/53.
