### ISSUE TITLE
Integrate new data-private submodule work with Hub

### ISSUE THREAD

**Issue by mtorres253** [18F/hub#499]
This story is to hook up Team API to the Hub before the migration is done. The Hub will need to expect the change and get its data from the new location.

Everything that the Hub is currently pulling directly from the team and project directories are now being pulled in via a Team API response.

To Demo: Make sure the Hub looks the same or better after this work is done. It should at least contain all the data it currently contains.

To Demo: 

After data-private migration:
https://github.com/18F/team-api.18f.gov/issues/166
https://github.com/18F/team-api.18f.gov/issues/167

This should still work

**Comment by mtorres253** [comment]
Hi Catherine, is this in progress?

**Comment by catherinedevlin** [comment]
It is in progress!  I haven't come to a sane point to push a branch up to github yet - probably tomorrow, though.

**Comment by mtorres253** [comment]
Thanks @catherinedevlin moving to in progress column

**Comment by mtorres253** [comment]
Does someone need to review this or can I close it?
