### ISSUE TITLE
Conduct interviews to inform personas

### ISSUE THREAD

**Issue by andrewmaier** [18F/hub#507]
In order to better inform our understanding of the people at 18F and how we might serve them, let's chat with:
##### Leadership
- [x] Eric Maland - 1/14/16 (Andrew)
- [x] Holly Allen - 1/11/16 (Michael)
- [x] ~~Chris Cairns~~ Tom Black - 1/13/16 (Andrew)
- [x] Jen Tress - 1/13/16 (Andrew)

##### Product team
- [x] Raphy Villas (CHI) - 1/12/16 (Michael)
- [x] Michelle Hertzfeld (TUC) - 1/14/16 (Andrew)
- [x] Nick Brethauer (DC) - 1/15/16 (Andrew)
- [x] Larry Bafundo (SF) - 1/8/16 (Michael)
- [x] Alan Atlas (SEA) - 1/7/16 (Michael)

##### Intake / business dev
- [x] Anna Heller Sebok - 1/15/16 (Andrew)
- [x] Will Slack  - 1/8/16 (Andrew)
- [x] Stephanie Rivera
- [x] ~~Someone (or a few people) who do tech evals?~~ Alex Bisker (Andrew)

Assuming there're no scheduling snafus, these interviews can likely be done by 1/8, transcribed by 1/15, and persona-fied by 1/20. We'll need to write/adapt some scripts for each group and migrate everything to [our persona map](https://docs.google.com/document/d/1eClRDfacMFcWnwtXQu3RBOKBSEx1zGB37YVXTTCw4hU/edit#) once we're done.

**Comment by mtorres253** [comment]
Let's take a look at this list and include a more diverse group of people at least in product and intake. We aim to get this research done by the end of this week, and transcribe the interviews by end of next week.

**Comment by andrewmaier** [comment]
I'll talk to everyone in **Leadership** except Holly Allen. I'll also talk to Michelle Hertzfeld (on Monday, in San Diego) and Anna Sebok.

**Comment by mtorres253** [comment]
Let's schedule interviews and give ourselves a week to synthesize and finish personas and persona map

**Comment by mtorres253** [comment]
Hi @andrewmaier are we still waiting to interview Nick and Chris? If so, I suggest we move this to done and not pursue those interviews. I think we have a lot of good coverage with the interviews we did. What do you think?

**Comment by andrewmaier** [comment]
Hey @mtorres253 Sorry for the delay! I've chatted with Nick; he's reviewing the transcript. I've also chatted with @blacktm in lieu of talking to @cscairns (we did try and meet multiple times). I just sent an invite out to @abisker to sure up our coverage of business dev / intake.

**Comment by mtorres253** [comment]
Hi @andrewmaier this looks like it's ready to move over. All the interviews are done. If you're OK with that, I'll add another story for personas

**Comment by andrewmaier** [comment]
@mtorres253 Let's do it!

**Comment by mtorres253** [comment]
Going to reopen until the @abisker interview is transcribed

**Comment by andrewmaier** [comment]
@mtorres253 Thanks! Sorry about that oversight!

**Comment by andrewmaier** [comment]
@mtorres253 This story is now done! I'm going to code @abisker's interview and update our personas.
