### ISSUE TITLE
Update contributing.md so that people know how to contribute

### ISSUE THREAD

**Issue by mtorres253** [18F/hub#519]
So that people know how to contribute to the Handbook, it should be made clear that they should do that via the Handbook repo (or :evergreen:). We need to figure out how/if we are allowing new pages to be created on the Hub, and how we want to handle updating pages that still live on the Hub (until they move out)

Acceptance Criteria:

**Comment by nicoleslaw** [comment]
This is mentioned here: https://github.com/18f/handbook, but could probably be clearer in the handbook's contributing file.

**Comment by nicoleslaw** [comment]
Tracking in https://github.com/18F/handbook/issues/75
