### ISSUE TITLE
Search results page

### ISSUE THREAD

**Issue by mtorres253** [18F/hub#526]
So that all users can see important details of their search matches, we should  display the results in a useful way.

Acceptance criteria:
I am an authenticated 18F employee
I am on the hub homepage (hub.18F.gov)
I type a string in the search box and press the enter key
Results come back that match the string I entered
I should see the following results displayed on the UI

1. Title 
2. Content snippet
3. Source (Handbook, Guide, etc)

**Comment by jbarnicle** [comment]
Making some progress here - hoping to have a demo version by EOD 3/8/2016

**Comment by jbarnicle** [comment]
Getting the last updated info (date/person) - might be tricky.  I think this will require doing a git log command on each file to retrieve this information.

**Comment by mtorres253** [comment]
Issue moved to [18F/hub-v2 #16](https://github.com/18F/hub-v2/issues/16) via [**ZenHub.io**](https://www.zenhub.io/)
