### ISSUE TITLE
Team/project graph page

### ISSUE THREAD

**Issue by mtorres253** [18F/hub#535]
As someone in 18F leadership, or business development, I want to have easy ways to see who is working on what, so that I can more easily staff projects or just get information about a particular project.

Acceptance criteria:
We have team and project data coming back already from Team API.  I should be able to see a team index page, and I should be able to click on a team member and see that team member's details.

Suggestion:
New repo for the index and team detail pages?

**Comment by mtorres253** [comment]
This seems to be in progress @andrewmaier but correct me if I'm wrong

**Comment by mtorres253** [comment]
Link to prototype:
https://pages-internal.18f.gov/hub-prototype/team/

**Comment by mbland** [comment]
Pretty groovy!

**Comment by catherinedevlin** [comment]
New repo for this work at http://github.com/18f/team-browser

**Comment by mtorres253** [comment]
Hi @catherinedevlin This looks like it might be ready to move to the "needs review" column. Is that the case?

**Comment by catherinedevlin** [comment]
sooooo close.  One stubborn ci_build error still getting in the way, though.  :(
