### ISSUE TITLE
Investigate adding update functionality to lunr.js server

### ISSUE THREAD

**Issue by mtorres253** [18F/hub#544]
Investigate how to get the lunr.js server to update when content is added or changed. Watch certain repos to see if content is added or changed. Future stage is to listen for creation of content repos.

https://github.com/18F/lunr-server/

@catherinedevlin and @mbland will pair. Let's give it a day. We want a list of action items that we can turn into stories

**Comment by mtorres253** [comment]
Hi @catherinedevlin are you at a place where you can document the action items? If so,  would you create any stories so that we can prioritize and schedule at the planning meeting? Let me know if you have any questions

**Comment by catherinedevlin** [comment]
1. Code that does the updating: DONE - https://github.com/18F/lunr-server/pull/2
2. Automated tests - underway

Should be finished by COB today.

**Comment by mtorres253** [comment]
@catherinedevlin does this need a review? or can it be closed

**Comment by catherinedevlin** [comment]
Ah - this was completed by https://github.com/18F/lunr-server/pull/2 and merged into lunr-server, so closing.
