### ISSUE TITLE
Synthesize research from design studio

### ISSUE THREAD

**Issue by mtorres253** [18F/hub#551]
So that this team can move forward on our short term roadmap, let's summarize the outcome of our design studio in a way that can help us do that

Acceptance criteria: 
Having a draft design strategy, incorporating the outputs of the design studio in the Hub Vignettes

**Comment by andrewmaier** [comment]
I've long since incorporated the output of the design studio into the Hub Vignettes. I haven't had a chance to really take stock of and incorporate the existing documentation into our design strategy.

**Comment by mtorres253** [comment]
@andrewmaier is this ready to move to done?
