### ISSUE TITLE
Filtering for team graph

### ISSUE THREAD

**Issue by mtorres253** [18F/hub#554]
As an 18F employee or member of the public, so that I can better locate team members with a certain skill or in a certain location, I should be able to quickly filter my view to see only those people with that skill or interest.

Acceptance Criteria:
I am an 18F employee or a member of the public 
And I'm viewing the team browser homepage
I see checkboxes for skills, interests and location
I check on two skills, one interest and one location (Ruby & Javascript, Accessibility, Chicago)
I click on the filter button
The index page is filtered to show only those employees who know Ruby AND Javascript, who are interested in Accessbility, and who are in Chicago

Notes: We are starting with OR joins within locations just AND joins within and between categories otherwise

**Comment by catherinedevlin** [comment]
work underway in https://github.com/18F/team-browser/tree/filters

**Comment by catherinedevlin** [comment]
https://github.com/18F/team-browser/pull/5

**Comment by mtorres253** [comment]
We are going to investigate testing for this to be done
