### ISSUE TITLE
I see links on the Hub homepage to most visited content still on the Hub

### ISSUE THREAD

**Issue by mtorres253** [18F/hub#564]
So that 18F employees still have access to content that is not yet migrated from the Hub to its own location, there should be a section of the homepage with links to most popular existing Hub content.

Acceptance criteria: 
I am an authenticated user of the Hub
I navigate to hub.18F.gov
I see a section containing links to most requested Hub pages
I see links to the following pages (in order)

1. [Intake](https://handbook.18f.gov/project-intake-101/)
2. [Checklists](https://checklistomania.apps.cloud.gov/)
3. [How we work](https://handbook.18f.gov/#how-we-work)
4. [Networks](https://handbook.18f.gov/networks/)
5. [Guidelines](https://handbook.18f.gov/bookmarks/#guides-and-standards)
6. [Acano workflows](https://handbook.18f.gov/acano/)
7. [Professional development and training](https://handbook.18f.gov/professional-development-and-training/)
8. [Float](https://handbook.18f.gov/float/)
9. [18F Structure](https://handbook.18f.gov/#about-us)
10. [Slack](https://handbook.18f.gov/slack/)

**Comment by mtorres253** [comment]
@nicoleslaw will verify this list first

**Comment by nicoleslaw** [comment]
A few link updates:
- I combined the Intake info here: https://handbook.18f.gov/project-intake-101/
- Checklist: https://checklistomania.apps.cloud.gov/

Is this useful? https://hub.18f.gov/guidelines/ -- why don't I just add those to handbook.18f.gov/bookmarks if so?

**Comment by nicoleslaw** [comment]
Just an update that the hub /guidelines are now under https://handbook.18f.gov/bookmarks — some are out of date, so I removed those or updated the links, etc.

**Comment by mtorres253** [comment]
This looks like it's done. Ready to move over @andrewmaier?

**Comment by andrewmaier** [comment]
Yup!
