### ISSUE TITLE
Style team browser

### ISSUE THREAD

**Issue by mtorres253** [18F/hub#569]
This story is just to style the team browser that catherine has been working on so that it looks more like the following:

https://pages-internal.18f.gov/hub-prototype/team/

Acceptance criteria: Andrew is please with how the team browser looks! And, filters are hidden for now, since they aren't working yet. Team index page, team member page, location page, project page, skills page.

**Comment by andrewmaier** [comment]
Hey @catherinedevlin Can we pair on this?
