### ISSUE TITLE
URL for filtered team results can be shared

### ISSUE THREAD

**Issue by mtorres253** [18F/hub#572]
As an 18F employee or member of the public, so that I can quickly share a page with someone else containing filtered search results, I should be able to copy and paste the URL and send it to another employee

Acceptance Criteria: 
I am an 18F employee or a member of the public
I am on the team browser index page
I have filtered for all employees who are skilled at Ruby and Javascript and live in Chicago 
There are results on my page
I copy the URL in my browser window and send it to someone else
When that employee clicks on the URL, they see the same filtered results I see

**Comment by catherinedevlin** [comment]
work underway in https://github.com/18F/team-browser/tree/filters

**Comment by catherinedevlin** [comment]
https://github.com/18F/team-browser/pull/5
