### ISSUE TITLE
Investigate elasticsearch as an alternative to lunr.js server

### ISSUE THREAD

**Issue by mtorres253** [18F/hub#578]
Investigate moving search from lunr.js to elasticsearch

**Comment by mtorres253** [comment]
Issue moved to [18F/hub-v2 #14](https://github.com/18F/hub-v2/issues/14) via [**ZenHub.io**](https://www.zenhub.io/)

**Comment by sandrobilbeisi** [comment]
sorry for chiming in a year late , but have you appraised ElasticLunr http://elasticlunr.com ?
