### ISSUE TITLE
Investigate testing options for front-end

### ISSUE THREAD

**Issue by mtorres253** [18F/hub#579]
Q-unit, jasmine, mocha chai as options? This story is to investigate a framework for unit testing.

**Comment by ertzeid** [comment]
Summary of what I've found:
- Jasmine, Mocha, and QUnit seem to be the most popular frameworks.
- While Mocha does work for all frameworks, it doesn't include its own matchers.
- Jasmine looks like the most popular overall, based on GitHub stars (10k, vs 8k for Mocha and 3k for QUnit)

Based on the above and the Front End Guild's recommendation to favor more popular tools (https://pages.18f.gov/frontend/recommendations/ under "Choosing a Tool"), I recommend using Jasmine for JavaScript testing.

**Comment by ertzeid** [comment]
... Does this story include setting up the framework? I can't remember what we discussed. cc: @mtorres253

**Comment by mtorres253** [comment]
I believe this is done @ertzeid? If so can you move to done?
