### ISSUE TITLE
Anchor links aren't working

### ISSUE THREAD

**Issue by nicoleslaw** [18F/hub#587]
Previously, the anchor links in the handbook would work two ways, for example: #heading-2 or #heading-name. The second style doesn't seem to be working anymore. Example: https://handbook.18f.gov/travel-101/#travel-card

**Comment by andrewmaier** [comment]
@nicoleslaw I don't think anyone's changed this code that adds the "heading-x" `id`s to the heading elements. You can manually add an `id` to any heading if you want to give it a specific name. If you do, that element doesn't get an auto-generated ("heading-x") `id`.

**Comment by nicoleslaw** [comment]
Shouldn't `<a name="setup"></a>` work here as well? I am so confused as to why it stopped working. https://handbook.18f.gov/github/#setup

**Comment by andrewmaier** [comment]
I believe you want `<a id="setup">`

**Comment by nicoleslaw** [comment]
I tried that first...reverted and it's still not working: https://handbook.18f.gov/github/#setup

**Comment by nicoleslaw** [comment]
The links are even more confusing now, ex: https://handbook.18f.gov/equipment/#a-idleaving-18fleaving-18fa

**Comment by andrewmaier** [comment]
@nicoleslaw So in this case we should remove the anchors surrounding the headings if at all possible. Otherwise I can rewrite the code to anticipate anchors around headings.

**Comment by nicoleslaw** [comment]
I don't understand why it was working either way (with or without an anchor link id)—and now it isn't working :(

**Comment by andrewmaier** [comment]
@nicoleslaw Looking into it right now. My hunch is that the code is creating invalid HTML which confuses the browser.
