### ISSUE TITLE
As a contributor, I would like to see analytics on what pages are most visited...

### ISSUE THREAD

**Issue by ultrasaurus** [18F/hub#63]
then I might spend more time making those great

**Comment by afeld** [comment]
Already done!

https://www.google.com/analytics/web/?authuser=1#report/content-pages/a48605964w80166384p82926493/%3Fexplorer-table.filter%3Dhub%26explorer-table.plotKeys%3D%5B%5D/

(you will need to log in w/ your GSA email, and you may need to remove the `?authuser=1` part from the URL)

**Comment by afeld** [comment]
![screen shot 2015-01-15 at 2 33 23 pm](https://cloud.githubusercontent.com/assets/86842/5764913/832cca58-9cc3-11e4-8192-45cc09fa41e4.png)

**Comment by afeld** [comment]
FYI, the pageviews for the private instance are in there as well (e.g. for `/snippets/`), but they are a bit difficult to tease apart since only the paths are shown. Maybe we can [include the full URL](https://support.google.com/analytics/answer/1012243?hl=en) for 18f.gsa.gov analytics, to more easily distinguish the internal vs. external Hub?

**Comment by brethauer** [comment]
cc @gbinal

**Comment by dhcole** [comment]
One option is a custom segment, such as the following:

![screen shot 2015-01-21 at 5 07 12 pm](https://cloud.githubusercontent.com/assets/170641/5846267/656fb71a-a190-11e4-9f95-28240460b48a.png)

Which enables comparisons between segments:

![screen shot 2015-01-21 at 5 08 53 pm](https://cloud.githubusercontent.com/assets/170641/5846269/691b3772-a190-11e4-9452-981971fd63f1.png)

**Comment by dhcole** [comment]
Relevant view for top content:

![screen shot 2015-01-21 at 5 13 44 pm](https://cloud.githubusercontent.com/assets/170641/5846333/e43e8224-a190-11e4-83dc-6b4c04b35b4b.png)
