### ISSUE TITLE
go serve command fails without submodules

### ISSUE THREAD

**Issue by kaitlin** [18F/hub#79]
When running 
`./go serve`

after running 
`./go init`

but before initializing the submodules, I get the following:

`canonicalizer.rb:90:in `block in sort_by_last_name!': undefined method `downcase' for nil:NilClass (NoMethodError)`

It works with the submodules.

**Comment by mbland** [comment]
Hmm, I just made a completely fresh clone, ran `./go init` and `./go serve` and haven't been able to reproduce. This is on the current `master` branch at 19857b6ec7252d927897a19ea3e32b8204341f4f. Can you try again with a completely fresh clone and/or paste more of the stack trace?

**Comment by mbland** [comment]
Going to close this as I haven't been able to reproduce it in a fresh clone. @kaitlin, please re-open if you're still having problems, and/or reach out to me to take a look in-person.
