### ISSUE TITLE
Changes/additions to New Hire Pro Tips

### ISSUE THREAD

**Issue by meiqimichelle** [18F/hub#93]
While we're transitioning the info from the New Hire Pro Tips doc over to the hub, please use this issue to record and edits or additions you'd like to make. That way, they won't get lost in the cracks! You can also open a new issue in this repo if you like -- whatever works for you :) Thanks!

**Comment by wslack** [comment]
I've finished going through this document and making sure everything is/was on the hub. I think this can be closed.
